general.import = [
  "~/.config/alacritty/themes/themes/citylights.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

[font]
# /Users/visual_partner/Library/Fonts
#normal.family = "BlexMono Nerd Font Mono"#"Inconsolata for Powerline"
#normal.family = "Cousine Nerd Font"
#normal.family = "CommitMono Nerd Font Propo"
normal.family = "CodeNewRoman Nerd Font"

size = 18

[cursor.style]
shape = "Beam"
blinking = "Always"


